---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wietforu/public_html/
    - export NODEJS_VERSION=20
    - export NODE_PATH=/home/wietforu/nodevenv/public_html/20/lib/node_modules
    - export PATH=/home/wietforu/nodevenv/public_html/20/bin:$PATH
    - source /home/wietforu/nodevenv/public_html/20/bin/activate
    - npm install
    - npm run build
    - cp -R dist/* $DEPLOYPATH
    - echo 'Options -MultiViews\nRewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteRule ^ index.html [QSA,L]' > $DEPLOYPATH/.htaccess
    - chmod 644 $DEPLOYPATH/.htaccess
    - find $DEPLOYPATH -type f -name "*.html" -exec chmod 644 {} \;
    - find $DEPLOYPATH -type f -name "*.css" -exec chmod 644 {} \;
    - find $DEPLOYPATH -type f -name "*.js" -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;