<?php
/**
 * LLMs.txt Generator
 * Creates /llms.txt file for AI crawler discovery
 * See: https://llmstxt.org/
 */

if (!defined('ABSPATH')) {
    exit;
}

class WPWorld_AI_LLMs_Txt {
    
    /**
     * Initialize hooks
     */
    public function init() {
        add_action('init', [$this, 'add_rewrite_rules']);
        add_filter('query_vars', [$this, 'add_query_vars']);
        add_action('template_redirect', [$this, 'serve_llms_txt']);
        
        // Also intercept early for hosts that don't support rewrite rules
        add_action('parse_request', [$this, 'intercept_llms_request'], 1);
    }
    
    /**
     * Add rewrite rule for llms.txt
     */
    public function add_rewrite_rules() {
        add_rewrite_rule('^llms\.txt/?$', 'index.php?wpworld_llms_txt=1', 'top');
    }
    
    /**
     * Intercept llms.txt request early (fallback for hosts without proper rewrites)
     */
    public function intercept_llms_request($wp) {
        $request_uri = $_SERVER['REQUEST_URI'] ?? '';
        
        // Check if this is a llms.txt request
        if (preg_match('#/llms\.txt/?$#i', $request_uri) || $request_uri === '/llms.txt') {
            $this->serve_llms_txt_direct();
        }
    }
    
    /**
     * Serve llms.txt directly (bypasses rewrite rules)
     */
    private function serve_llms_txt_direct() {
        header('Content-Type: text/plain; charset=utf-8');
        header('X-Robots-Tag: noindex');
        
        echo $this->generate_content();
        exit;
    }
    
    /**
     * Add query var
     */
    public function add_query_vars($vars) {
        $vars[] = 'wpworld_llms_txt';
        return $vars;
    }
    
    /**
     * Serve llms.txt content
     */
    public function serve_llms_txt() {
        if (!get_query_var('wpworld_llms_txt')) {
            return;
        }
        
        header('Content-Type: text/plain; charset=utf-8');
        header('X-Robots-Tag: noindex');
        
        echo $this->generate_content();
        exit;
    }
    
    /**
     * Generate llms.txt content
     */
    public function generate_content() {
        $site_name = get_bloginfo('name');
        $site_description = get_bloginfo('description');
        $site_url = home_url('/');
        $ai_summary_url = home_url('/ai-summary/');
        
        // Get AI summary data if available
        $ai_summary = new WPWorld_AI_AI_Summary();
        $summary_data = $ai_summary->get_summary_data();
        
        $content = "# {$site_name}\n\n";
        $content .= "> {$site_description}\n\n";
        
        $content .= "## About\n\n";
        if (!empty($summary_data['content'])) {
            // First 500 chars of AI summary
            $about = wp_trim_words(strip_tags($summary_data['content']), 80, '...');
            $content .= "{$about}\n\n";
        } else {
            $content .= "Visit our website to learn more about our services and offerings.\n\n";
        }
        
        $content .= "## Key Information\n\n";
        $content .= "- **Website**: {$site_url}\n";
        $content .= "- **AI Summary**: {$ai_summary_url}\n";
        
        // Add sitemap
        $sitemap_url = home_url('/wp-sitemap.xml');
        $content .= "- **Sitemap**: {$sitemap_url}\n";
        
        // Add contact if available
        $admin_email = get_option('admin_email');
        if ($admin_email && get_option('wpworld_ai_show_contact', false)) {
            $content .= "- **Contact**: {$admin_email}\n";
        }
        
        $content .= "\n## Topics & Keywords\n\n";
        if (!empty($summary_data['keywords'])) {
            $content .= implode(', ', $summary_data['keywords']) . "\n\n";
        } else {
            // Get categories as fallback
            $categories = get_categories(['hide_empty' => true, 'number' => 10]);
            if (!empty($categories)) {
                $cat_names = array_map(function($cat) { return $cat->name; }, $categories);
                $content .= implode(', ', $cat_names) . "\n\n";
            }
        }
        
        // FAQ section
        if (!empty($summary_data['faq'])) {
            $content .= "## Frequently Asked Questions\n\n";
            foreach (array_slice($summary_data['faq'], 0, 5) as $faq) {
                $content .= "**Q: {$faq['question']}**\n";
                $content .= "A: {$faq['answer']}\n\n";
            }
        }
        
        $content .= "---\n";
        $content .= "Generated by WPWorld AI Visibility\n";
        $content .= "Last updated: " . current_time('Y-m-d') . "\n";
        
        return $content;
    }
    
    /**
     * Check if llms.txt is accessible
     */
    public function is_accessible() {
        $url = home_url('/llms.txt');
        $response = wp_remote_head($url, ['timeout' => 5]);
        
        if (is_wp_error($response)) {
            return false;
        }
        
        return wp_remote_retrieve_response_code($response) === 200;
    }
    
    /**
     * Get llms.txt URL
     */
    public function get_url() {
        return home_url('/llms.txt');
    }
    
    /**
     * Flush rewrite rules (call on plugin activation)
     */
    public static function activate() {
        $instance = new self();
        $instance->add_rewrite_rules();
        flush_rewrite_rules();
    }
}
